using Microsoft.EntityFrameworkCore;
using SPage.Application.Common.Interfaces;
using SPage.Domain.Entities.Blog;
using SPage.Domain.Entities.Product;
using SPage.Domain.Entities.Store;
using SPage.Domain.Enums;
using SPage.Infrastructure.Persistence;

namespace SPage.Web.SeedData;

internal static partial class DataSeeder
{
    /// <summary>
    /// Seed dữ liệu mẫu: danh mục, sản phẩm, bài viết, cửa hàng.
    /// Idempotent — bỏ qua nếu đã có dữ liệu.
    /// </summary>
    public static async Task SeedSampleDataAsync(IServiceProvider services)
    {
        using var scope    = services.CreateScope();
        var context        = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        var slugService    = scope.ServiceProvider.GetRequiredService<ISlugService>();

        if (await context.Categories.AnyAsync() ||
            await context.Products.AnyAsync()   ||
            await context.Posts.AnyAsync())
            return;

        // ── Blog Categories ───────────────────────────────────────────────────
        var catNews    = new Category { Name = "Tin tức sự kiện", Slug = slugService.Generate("Tin tức sự kiện"),    Description = "Tin tức và sự kiện mới nhất của Tân Huê Viên",                                   IsIndexable = true };
        var catExport  = new Category { Name = "Xuất khẩu",       Slug = slugService.Generate("Xuất khẩu"),          Description = "Thông tin về hoạt động xuất khẩu sản phẩm ra thị trường quốc tế",              IsIndexable = true };
        var catProduct = new Category { Name = "Sản phẩm mới",    Slug = slugService.Generate("Sản phẩm mới"),       Description = "Giới thiệu các sản phẩm mới của Tân Huê Viên",                                  IsIndexable = true };
        context.Categories.AddRange(catNews, catExport, catProduct);

        // ── Product Categories ────────────────────────────────────────────────
        var pcBanhPia      = new ProductCategory { Name = "Bánh Pía Truyền Thống", Slug = slugService.Generate("Bánh Pía Truyền Thống"), Description = "Bánh pía truyền thống đặc sản Sóc Trăng với nhiều hương vị phong phú",          IsIndexable = true };
        var pcBanhPiaChay  = new ProductCategory { Name = "Bánh Pía Chay",         Slug = slugService.Generate("Bánh Pía Chay"),         Description = "Bánh pía chay dành cho người ăn chay, nhiều hương vị tự nhiên",                  IsIndexable = true };
        var pcLapXuong     = new ProductCategory { Name = "Lạp Xưởng",             Slug = slugService.Generate("Lạp Xưởng"),             Description = "Lạp xưởng Tân Huê Viên với nhiều hương vị đặc trưng",                          IsIndexable = true };
        var pcSanPhamMoi   = new ProductCategory { Name = "Sản Phẩm Mới",          Slug = slugService.Generate("Sản Phẩm Mới"),          Description = "Các sản phẩm mới ra mắt năm 2025 của Tân Huê Viên",                            IsIndexable = true };
        var pcBanhKimSa    = new ProductCategory { Name = "Bánh Pía Kim Sa",        Slug = slugService.Generate("Bánh Pía Kim Sa"),        Description = "Bánh pía kim sa cao cấp với lớp vỏ ánh vàng sang trọng",                       IsIndexable = true };
        var pcBanhPiaMini  = new ProductCategory { Name = "Bánh Pía nhỏ (Mini)",   Slug = slugService.Generate("Bánh Pía nhỏ Mini"),      Description = "Bánh pía cỡ nhỏ tiện lợi, thích hợp làm quà tặng",                            IsIndexable = true };
        var pcBanhTrungThu = new ProductCategory { Name = "Bánh Trung Thu",         Slug = slugService.Generate("Bánh Trung Thu"),         Description = "Bánh trung thu Tân Huê Viên theo phong cách truyền thống",                    IsIndexable = true };
        var pcKeo          = new ProductCategory { Name = "Kẹo",                    Slug = slugService.Generate("Kẹo"),                    Description = "Các loại kẹo đặc sản của Tân Huê Viên",                                        IsIndexable = true };
        var pcCaPhe        = new ProductCategory { Name = "Cà Phê",                 Slug = slugService.Generate("Cà Phê"),                 Description = "Cà phê đặc sản của Tân Huê Viên",                                              IsIndexable = true };

        context.ProductCategories.AddRange(
            pcBanhPia, pcBanhPiaChay, pcLapXuong, pcSanPhamMoi,
            pcBanhKimSa, pcBanhPiaMini, pcBanhTrungThu, pcKeo, pcCaPhe);
        await context.SaveChangesAsync(CancellationToken.None);

        // ── Products ──────────────────────────────────────────────────────────
        var products = new List<Product>
        {
            // Bánh Pía Truyền Thống
            new() { Name = "Bánh Pía Khoai Môn Sầu Riêng Trứng",                Slug = slugService.Generate("Bánh Pía Khoai Môn Sầu Riêng Trứng"),               Price = 185000, CategoryId = pcBanhPia.Id,     IsActive = true, IsFeatured = true, SortOrder = 1, ShortDescription = "Bánh pía nhân khoai môn, sầu riêng và trứng muối – kết hợp hương vị đậm đà truyền thống.", Description = "<p>Bánh pía khoai môn sầu riêng trứng là một trong những sản phẩm bán chạy nhất của Tân Huê Viên. Nhân bánh được làm từ khoai môn tươi, sầu riêng nguyên chất kết hợp lòng đỏ trứng muối thơm bùi. Vỏ bánh nhiều lớp giòn xốp đặc trưng, mang đậm hương vị truyền thống Sóc Trăng.</p>", MetaTitle = "Bánh Pía Khoai Môn Sầu Riêng Trứng - Tân Huê Viên",    MetaDescription = "Bánh pía khoai môn sầu riêng trứng muối Tân Huê Viên – đặc sản Sóc Trăng chính gốc, nhân thơm bùi, vỏ giòn xốp." },
            new() { Name = "Bánh Pía Mè Đen",                                    Slug = slugService.Generate("Bánh Pía Mè Đen"),                                   Price = 165000, CategoryId = pcBanhPia.Id,     IsActive = true,                    SortOrder = 2, ShortDescription = "Bánh pía nhân mè đen thơm ngào ngạt, vỏ giòn xốp nhiều lớp.", Description = "<p>Bánh pía mè đen Tân Huê Viên với nhân mè đen rang thơm, ngọt thanh. Vỏ bánh được làm thủ công nhiều lớp, giòn tan khi cắn. Phù hợp làm quà biếu tặng trong các dịp lễ Tết.</p>", MetaTitle = "Bánh Pía Mè Đen - Tân Huê Viên",                         MetaDescription = "Bánh pía mè đen Tân Huê Viên – nhân mè đen thơm, vỏ giòn xốp, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía Đậu Xanh Sầu Riêng Trứng",                 Slug = slugService.Generate("Bánh Pía Đậu Xanh Sầu Riêng Trứng"),                 Price = 175000, CategoryId = pcBanhPia.Id,     IsActive = true, IsFeatured = true, SortOrder = 3, ShortDescription = "Nhân đậu xanh mịn kết hợp sầu riêng và trứng muối béo bùi.", Description = "<p>Bánh pía đậu xanh sầu riêng trứng – sự kết hợp hoàn hảo giữa đậu xanh bùi béo, sầu riêng thơm nồng và trứng muối đậm đà. Một trong những hương vị kinh điển của bánh pía Tân Huê Viên.</p>", MetaTitle = "Bánh Pía Đậu Xanh Sầu Riêng Trứng - Tân Huê Viên",      MetaDescription = "Bánh pía đậu xanh sầu riêng trứng muối Tân Huê Viên – hương vị kinh điển, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía 6 Sao",                                     Slug = slugService.Generate("Bánh Pía 6 Sao"),                                    Price = 220000, CategoryId = pcBanhPia.Id,     IsActive = true, IsFeatured = true, SortOrder = 4, ShortDescription = "Bánh pía cao cấp 6 sao – tinh hoa ẩm thực Sóc Trăng.", Description = "<p>Bánh pía 6 sao là dòng sản phẩm cao cấp của Tân Huê Viên, được chế biến từ nguyên liệu chọn lọc kỹ lưỡng. Hương vị phong phú, vỏ bánh mỏng giòn, nhân mềm mịn thơm ngon, thích hợp làm quà biếu cao cấp.</p>", MetaTitle = "Bánh Pía 6 Sao Tân Huê Viên - Cao Cấp Đặc Biệt",         MetaDescription = "Bánh pía 6 sao Tân Huê Viên – dòng sản phẩm cao cấp, nguyên liệu tuyển chọn, hương vị tinh tế." },
            new() { Name = "Bánh Pía Đậu Sầu Riêng Trứng - Diện Mạo Mới 2025",  Slug = slugService.Generate("Bánh Pía Đậu Sầu Riêng Trứng Diện Mạo Mới 2025"),    Price = 180000, CategoryId = pcBanhPia.Id,     IsActive = true, IsNew = true,       SortOrder = 5, ShortDescription = "Công thức kinh điển đậu sầu riêng trứng với bao bì hoàn toàn mới 2025.", Description = "<p>Giữ nguyên công thức truyền thống yêu thích – nhân đậu mịn, sầu riêng thơm nồng, trứng muối béo bùi – nay khoác lên mình diện mạo bao bì hiện đại, sang trọng của năm 2025.</p>", MetaTitle = "Bánh Pía Đậu Sầu Riêng Trứng Diện Mạo Mới 2025 - Tân Huê Viên", MetaDescription = "Bánh pía đậu sầu riêng trứng Tân Huê Viên với bao bì mới 2025 – hương vị kinh điển, hình ảnh hiện đại." },
            new() { Name = "Bánh Pía Đậu Đen Sầu Riêng Trứng",                  Slug = slugService.Generate("Bánh Pía Đậu Đen Sầu Riêng Trứng"),                  Price = 175000, CategoryId = pcBanhPia.Id,     IsActive = true,                    SortOrder = 6, ShortDescription = "Nhân đậu đen thơm bùi kết hợp sầu riêng và trứng muối đặc trưng.", Description = "<p>Bánh pía đậu đen sầu riêng trứng mang hương vị độc đáo với nhân đậu đen dẻo thơm, sầu riêng Ri6 nguyên chất và trứng muối hòa quyện. Vỏ bánh giòn xốp nhiều lớp theo công thức truyền thống.</p>", MetaTitle = "Bánh Pía Đậu Đen Sầu Riêng Trứng - Tân Huê Viên",       MetaDescription = "Bánh pía đậu đen sầu riêng trứng Tân Huê Viên – hương vị độc đáo, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía Số 1",                                       Slug = slugService.Generate("Bánh Pía Số 1"),                                     Price = 155000, CategoryId = pcBanhPia.Id,     IsActive = true,                    SortOrder = 7, ShortDescription = "Bánh pía số 1 – hương vị tiêu biểu nhất của Tân Huê Viên.", Description = "<p>Bánh pía Số 1 là sản phẩm đại diện của thương hiệu Tân Huê Viên, mang hương vị truyền thống đậm đà của đặc sản Sóc Trăng. Phù hợp làm quà cho mọi dịp.</p>", MetaTitle = "Bánh Pía Số 1 - Tân Huê Viên",                           MetaDescription = "Bánh pía Số 1 Tân Huê Viên – sản phẩm đại diện, hương vị truyền thống đặc sản Sóc Trăng." },

            // Bánh Pía Chay
            new() { Name = "Bánh Pía Chay Đậu Đỏ",    Slug = slugService.Generate("Bánh Pía Chay Đậu Đỏ"),    Price = 155000, CategoryId = pcBanhPiaChay.Id, IsActive = true,                    SortOrder = 1, ShortDescription = "Bánh pía chay nhân đậu đỏ ngọt bùi, thích hợp người ăn chay.", Description = "<p>Bánh pía chay đậu đỏ Tân Huê Viên – nhân đậu đỏ ngọt bùi tự nhiên, không sử dụng nguyên liệu động vật.</p>", MetaTitle = "Bánh Pía Chay Đậu Đỏ - Tân Huê Viên",    MetaDescription = "Bánh pía chay đậu đỏ Tân Huê Viên – thuần chay, nhân đậu đỏ ngọt bùi, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía Chay Dứa",        Slug = slugService.Generate("Bánh Pía Chay Dứa"),        Price = 155000, CategoryId = pcBanhPiaChay.Id, IsActive = true,                    SortOrder = 2, ShortDescription = "Bánh pía chay nhân dứa thanh mát, ngọt tự nhiên.", Description = "<p>Bánh pía chay dứa với nhân dứa tươi thanh mát, vị ngọt tự nhiên. Sản phẩm thuần chay, không chứa thành phần động vật.</p>", MetaTitle = "Bánh Pía Chay Dứa - Tân Huê Viên",        MetaDescription = "Bánh pía chay nhân dứa Tân Huê Viên – thuần chay, vị thanh mát, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía Chay Đậu Xanh",  Slug = slugService.Generate("Bánh Pía Chay Đậu Xanh"),  Price = 150000, CategoryId = pcBanhPiaChay.Id, IsActive = true,                    SortOrder = 3, ShortDescription = "Bánh pía chay nhân đậu xanh mịn béo, vỏ giòn xốp.", Description = "<p>Bánh pía chay đậu xanh mang hương vị quen thuộc với nhân đậu xanh mịn béo, vỏ bánh giòn xốp nhiều lớp. Sản phẩm thuần chay phù hợp mọi đối tượng.</p>", MetaTitle = "Bánh Pía Chay Đậu Xanh - Tân Huê Viên",  MetaDescription = "Bánh pía chay đậu xanh Tân Huê Viên – thuần chay, nhân mịn béo, vỏ giòn xốp." },
            new() { Name = "Bánh Pía Chay Mè Đen",    Slug = slugService.Generate("Bánh Pía Chay Mè Đen"),    Price = 155000, CategoryId = pcBanhPiaChay.Id, IsActive = true,                    SortOrder = 4, ShortDescription = "Bánh pía chay nhân mè đen rang thơm, ngọt thanh tự nhiên.", Description = "<p>Bánh pía chay mè đen với nhân mè đen rang thơm nức, vị ngọt thanh tự nhiên. Được chế biến hoàn toàn từ nguyên liệu thực vật.</p>", MetaTitle = "Bánh Pía Chay Mè Đen - Tân Huê Viên",    MetaDescription = "Bánh pía chay mè đen Tân Huê Viên – nhân mè đen thơm, thuần chay, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Pía Chay Môn",       Slug = slugService.Generate("Bánh Pía Chay Môn"),       Price = 160000, CategoryId = pcBanhPiaChay.Id, IsActive = true, IsFeatured = true, SortOrder = 5, ShortDescription = "Bánh pía chay nhân khoai môn dẻo thơm, được xuất khẩu tại Costco.", Description = "<p>Bánh pía chay môn – sản phẩm thuần chay với nhân khoai môn dẻo thơm ngọt bùi. Đã được xuất khẩu thành công sang thị trường Bắc Mỹ và có mặt tại Costco Canada.</p>", MetaTitle = "Bánh Pía Chay Môn - Tân Huê Viên",       MetaDescription = "Bánh pía chay môn Tân Huê Viên – thuần chay, nhân khoai môn thơm bùi, xuất khẩu Costco Canada." },
            new() { Name = "Bánh Pía Chay Thập Cẩm",  Slug = slugService.Generate("Bánh Pía Chay Thập Cẩm"),  Price = 160000, CategoryId = pcBanhPiaChay.Id, IsActive = true,                    SortOrder = 6, ShortDescription = "Bánh pía chay thập cẩm với hỗn hợp nhiều hương vị phong phú.", Description = "<p>Bánh pía chay thập cẩm là sự kết hợp hài hòa của nhiều loại nhân thực vật cao cấp: đậu xanh, khoai môn, mè đen và các nguyên liệu tự nhiên khác.</p>", MetaTitle = "Bánh Pía Chay Thập Cẩm - Tân Huê Viên",  MetaDescription = "Bánh pía chay thập cẩm Tân Huê Viên – đa hương vị, thuần chay, đặc sản Sóc Trăng." },
            new() { Name = "Bánh Song Vị Đậu - Dứa (NEW 2025)", Slug = slugService.Generate("Bánh Song Vị Đậu Dứa 2025"), Price = 170000, CategoryId = pcBanhPiaChay.Id, IsActive = true, IsNew = true, SortOrder = 7, ShortDescription = "Sản phẩm mới 2025 – nhân đôi vị đậu và dứa trong một chiếc bánh.", Description = "<p>Bánh song vị đậu - dứa là sản phẩm mới ra mắt năm 2025, mang trải nghiệm thú vị với hai tầng nhân đậu thơm bùi và dứa chua ngọt tự nhiên trong một chiếc bánh pía chay.</p>", MetaTitle = "Bánh Song Vị Đậu - Dứa 2025 - Tân Huê Viên", MetaDescription = "Bánh song vị đậu dứa Tân Huê Viên – sản phẩm mới 2025, hai hương vị trong một, thuần chay." },
            new() { Name = "Bánh Song Vị Đậu - Môn (NEW 2025)", Slug = slugService.Generate("Bánh Song Vị Đậu Môn 2025"),  Price = 170000, CategoryId = pcBanhPiaChay.Id, IsActive = true, IsNew = true, SortOrder = 8, ShortDescription = "Sản phẩm mới 2025 – nhân đôi vị đậu và khoai môn trong một chiếc bánh.", Description = "<p>Bánh song vị đậu - môn là sản phẩm mới của Tân Huê Viên năm 2025, kết hợp tầng nhân đậu bùi béo và khoai môn dẻo thơm. Thiết kế sáng tạo, hương vị độc đáo, phù hợp làm quà tặng.</p>", MetaTitle = "Bánh Song Vị Đậu - Môn 2025 - Tân Huê Viên", MetaDescription = "Bánh song vị đậu môn Tân Huê Viên – sản phẩm mới 2025, hai hương vị trong một, thuần chay." },

            // Lạp Xưởng
            new() { Name = "Lạp Xưởng Tươi",              Slug = slugService.Generate("Lạp Xưởng Tươi"),              Price = 120000, CategoryId = pcLapXuong.Id, IsActive = true, IsFeatured = true, SortOrder = 1, ShortDescription = "Lạp xưởng tươi Tân Huê Viên – thơm ngon, đậm đà hương vị truyền thống.", Description = "<p>Lạp xưởng tươi Tân Huê Viên được làm từ thịt heo tươi chọn lọc, ướp theo công thức gia truyền.</p>", MetaTitle = "Lạp Xưởng Tươi - Tân Huê Viên",              MetaDescription = "Lạp xưởng tươi Tân Huê Viên – thịt heo chọn lọc, ướp gia vị truyền thống, thơm ngon đậm đà." },
            new() { Name = "Lạp Xưởng Trứng Muối",        Slug = slugService.Generate("Lạp Xưởng Trứng Muối"),        Price = 135000, CategoryId = pcLapXuong.Id, IsActive = true,                    SortOrder = 2, ShortDescription = "Lạp xưởng kết hợp trứng muối – hương vị béo bùi độc đáo.", Description = "<p>Lạp xưởng trứng muối Tân Huê Viên là sự kết hợp sáng tạo giữa lạp xưởng truyền thống và lòng đỏ trứng muối béo bùi.</p>", MetaTitle = "Lạp Xưởng Trứng Muối - Tân Huê Viên",        MetaDescription = "Lạp xưởng trứng muối Tân Huê Viên – kết hợp độc đáo, béo bùi thơm ngon." },
            new() { Name = "Lạp Xưởng Xông Khói",         Slug = slugService.Generate("Lạp Xưởng Xông Khói"),         Price = 130000, CategoryId = pcLapXuong.Id, IsActive = true,                    SortOrder = 3, ShortDescription = "Lạp xưởng xông khói hương vị đặc trưng, thơm lừng.", Description = "<p>Lạp xưởng xông khói Tân Huê Viên được chế biến theo phương pháp xông khói truyền thống, tạo nên hương vị thơm đặc trưng khó quên.</p>", MetaTitle = "Lạp Xưởng Xông Khói - Tân Huê Viên",         MetaDescription = "Lạp xưởng xông khói Tân Huê Viên – hương khói đặc trưng, thơm ngon, tiện lợi." },
            new() { Name = "Lạp Xưởng Gà",                Slug = slugService.Generate("Lạp Xưởng Gà"),                Price = 115000, CategoryId = pcLapXuong.Id, IsActive = true,                    SortOrder = 4, ShortDescription = "Lạp xưởng gà ít béo, hương vị thanh ngon, tốt cho sức khỏe.", Description = "<p>Lạp xưởng gà Tân Huê Viên là lựa chọn lành mạnh hơn với thịt gà ít béo, ướp gia vị vừa vặn.</p>", MetaTitle = "Lạp Xưởng Gà - Tân Huê Viên",                MetaDescription = "Lạp xưởng gà Tân Huê Viên – ít béo, hương vị thanh ngon, lựa chọn lành mạnh." },
            new() { Name = "Lạp Xưởng Mai Quế Lộ",       Slug = slugService.Generate("Lạp Xưởng Mai Quế Lộ"),       Price = 140000, CategoryId = pcLapXuong.Id, IsActive = true,                    SortOrder = 5, ShortDescription = "Lạp xưởng mai quế lộ hương vị thơm đặc trưng của rượu mai quế.", Description = "<p>Lạp xưởng mai quế lộ Tân Huê Viên được ướp với rượu mai quế lộ thơm đặc trưng, tạo nên hương vị độc đáo không thể nhầm lẫn.</p>", MetaTitle = "Lạp Xưởng Mai Quế Lộ - Tân Huê Viên",       MetaDescription = "Lạp xưởng mai quế lộ Tân Huê Viên – hương thơm đặc trưng, vị đậm đà truyền thống." },
            new() { Name = "Lạp Xưởng Mai Quế Lộ Vị Tiêu 3 Sao", Slug = slugService.Generate("Lạp Xưởng Mai Quế Lộ Vị Tiêu 3 Sao"), Price = 150000, CategoryId = pcLapXuong.Id, IsActive = true, SortOrder = 6, ShortDescription = "Lạp xưởng mai quế lộ 3 sao với vị tiêu cay nồng hấp dẫn.", Description = "<p>Lạp xưởng mai quế lộ vị tiêu 3 sao là phiên bản cao cấp với vị tiêu cay nồng kết hợp hương thơm của rượu mai quế.</p>", MetaTitle = "Lạp Xưởng Mai Quế Lộ Vị Tiêu 3 Sao - Tân Huê Viên", MetaDescription = "Lạp xưởng mai quế lộ vị tiêu 3 sao Tân Huê Viên – cao cấp, cay nồng đặc trưng." },
            new() { Name = "Lạp Xưởng Ăn Liền",           Slug = slugService.Generate("Lạp Xưởng Ăn Liền"),           Price = 95000,  CategoryId = pcLapXuong.Id, IsActive = true,                    SortOrder = 7, ShortDescription = "Lạp xưởng ăn liền tiện lợi, thơm ngon, dùng được ngay.", Description = "<p>Lạp xưởng ăn liền Tân Huê Viên – tiện lợi, không cần chế biến thêm. Sản phẩm đã được sơ chế và chín sẵn.</p>", MetaTitle = "Lạp Xưởng Ăn Liền - Tân Huê Viên",           MetaDescription = "Lạp xưởng ăn liền Tân Huê Viên – tiện lợi, thơm ngon, không cần chế biến." },

            // Sản Phẩm Mới 2025
            new() { Name = "Bánh Kim Ngân (NEW 2025)",           Slug = slugService.Generate("Bánh Kim Ngân 2025"),        Price = 195000, CategoryId = pcSanPhamMoi.Id, IsActive = true, IsNew = true,                    SortOrder = 1, ShortDescription = "Sản phẩm mới 2025 – bánh kim ngân cao cấp, sang trọng.", Description = "<p>Bánh Kim Ngân là sản phẩm mới ra mắt năm 2025 của Tân Huê Viên, mang vẻ ngoài sang trọng với lớp vàng ánh kim đặc trưng.</p>", MetaTitle = "Bánh Kim Ngân 2025 - Tân Huê Viên",           MetaDescription = "Bánh Kim Ngân Tân Huê Viên – sản phẩm mới 2025, sang trọng, thích hợp làm quà tặng." },
            new() { Name = "Bánh Tiểu Long Châu (NEW 2025)",    Slug = slugService.Generate("Bánh Tiểu Long Châu 2025"),  Price = 185000, CategoryId = pcSanPhamMoi.Id, IsActive = true, IsNew = true,                    SortOrder = 2, ShortDescription = "Sản phẩm mới 2025 – bánh tiểu long châu hương vị tinh tế.", Description = "<p>Bánh Tiểu Long Châu – sản phẩm mới của Tân Huê Viên năm 2025 với hình dáng đẹp mắt và hương vị tinh tế đặc biệt.</p>", MetaTitle = "Bánh Tiểu Long Châu 2025 - Tân Huê Viên",    MetaDescription = "Bánh Tiểu Long Châu Tân Huê Viên – sản phẩm mới 2025, hình đẹp, vị ngon." },
            new() { Name = "Bánh Love (NEW 2025)",               Slug = slugService.Generate("Bánh Love 2025"),             Price = 175000, CategoryId = pcSanPhamMoi.Id, IsActive = true, IsNew = true,                    SortOrder = 3, ShortDescription = "Bánh hình trái tim 2025 – món quà ngọt ngào cho người thân.", Description = "<p>Bánh Love – sản phẩm mới 2025 của Tân Huê Viên với thiết kế hình trái tim đáng yêu, nhân bánh thơm ngon ngọt ngào.</p>", MetaTitle = "Bánh Love 2025 - Tân Huê Viên",               MetaDescription = "Bánh Love Tân Huê Viên – sản phẩm mới 2025, hình trái tim, ngọt ngào ý nghĩa." },
            new() { Name = "Hoàng Kim Đậu - Môn (NEW 2025)",    Slug = slugService.Generate("Hoàng Kim Đậu Môn 2025"),    Price = 200000, CategoryId = pcSanPhamMoi.Id, IsActive = true, IsNew = true, IsFeatured = true, SortOrder = 4, ShortDescription = "Sản phẩm mới 2025 – nhân đậu khoai môn cao cấp, vỏ ánh vàng sang trọng.", Description = "<p>Hoàng Kim Đậu - Môn là sản phẩm cao cấp mới ra mắt năm 2025, với lớp vỏ ánh vàng sang trọng và nhân đậu khoai môn thơm bùi.</p>", MetaTitle = "Hoàng Kim Đậu Môn 2025 - Tân Huê Viên",    MetaDescription = "Hoàng Kim Đậu Môn Tân Huê Viên – sản phẩm mới cao cấp 2025, vỏ vàng sang trọng." },
            new() { Name = "Hoàng Kim Đậu - Dứa (NEW 2025)",   Slug = slugService.Generate("Hoàng Kim Đậu Dứa 2025"),    Price = 200000, CategoryId = pcSanPhamMoi.Id, IsActive = true, IsNew = true, IsFeatured = true, SortOrder = 5, ShortDescription = "Sản phẩm mới 2025 – nhân đậu dứa cao cấp, vỏ ánh vàng sang trọng.", Description = "<p>Hoàng Kim Đậu - Dứa là phiên bản nhân dứa của dòng Hoàng Kim cao cấp, ra mắt năm 2025. Vỏ bánh ánh vàng sang trọng, nhân đậu dứa chua ngọt hấp dẫn.</p>", MetaTitle = "Hoàng Kim Đậu Dứa 2025 - Tân Huê Viên",    MetaDescription = "Hoàng Kim Đậu Dứa Tân Huê Viên – sản phẩm mới cao cấp 2025, vỏ vàng, nhân dứa ngọt." },
        };

        context.Products.AddRange(products);

        // ── Blog Posts ────────────────────────────────────────────────────────
        var posts = new List<Post>
        {
            new() { Title = "Tân Huê Viên Ký Kết Hợp Tác Chiến Lược Cùng Đối Tác Quảng Châu (Trung Quốc)", Slug = slugService.Generate("Tan Hue Vien Ky Ket Hop Tac Chien Luoc Cung Doi Tac Quang Chau Trung Quoc"), Excerpt = "Tân Huê Viên đã long trọng tổ chức Lễ ký kết hợp tác chiến lược cùng Công ty Đông Nam Á Quảng Châu tại thành phố Cần Thơ.", Content = "<p>Tại thành phố Cần Thơ, Công ty TNHH Chế Biến Thực Phẩm Bánh Pía - Lạp Xưởng Tân Huê Viên đã long trọng tổ chức Lễ ký kết hợp tác chiến lược cùng Công ty Đông Nam Á Quảng Châu (Trung Quốc). Đây là bước tiến quan trọng trong chiến lược mở rộng thị trường xuất khẩu của Tân Huê Viên sang thị trường Trung Quốc.</p>", Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2026, 2, 12, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Tân Huê Viên Ký Kết Hợp Tác Chiến Lược Với Đối Tác Quảng Châu", MetaDescription = "Tân Huê Viên ký kết hợp tác chiến lược với Công ty Đông Nam Á Quảng Châu, mở rộng xuất khẩu sang thị trường Trung Quốc." },
            new() { Title = "Tân Huê Viên Vinh Dự Đón Tiếp Thứ Trưởng Bộ Ngoại Giao Lê Thị Thu Hằng",      Slug = slugService.Generate("Tan Hue Vien Vinh Du Don Tiep Thu Truong Bo Ngoai Giao Le Thi Thu Hang"),      Excerpt = "Tân Huê Viên vinh dự được đón tiếp bà Lê Thị Thu Hằng – Thứ trưởng Bộ Ngoại giao Việt Nam đến thăm và tìm hiểu hoạt động sản xuất của công ty.", Content = "<p>Tân Huê Viên vinh dự được đón tiếp bà Lê Thị Thu Hằng - Thứ trưởng Bộ Ngoại giao Việt Nam đến thăm và làm việc. Chuyến thăm này ghi nhận nỗ lực của Tân Huê Viên trong việc đưa sản phẩm truyền thống Việt Nam ra thị trường quốc tế.</p>", Category = catNews,   Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 12, 17, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Tân Huê Viên Đón Tiếp Thứ Trưởng Bộ Ngoại Giao",                                    MetaDescription = "Tân Huê Viên đón tiếp Thứ trưởng Bộ Ngoại giao Lê Thị Thu Hằng tham quan nhà máy và tìm hiểu hoạt động xuất khẩu." },
            new() { Title = "Tân Huê Viên Góp Mặt Tại Hội Chợ Ẩm Thực Quốc Tế MIFB 2025 - Malaysia",       Slug = slugService.Generate("Tan Hue Vien Gop Mat Tai Hoi Cho Am Thuc Quoc Te MIFB 2025 Malaysia"),       Excerpt = "Tân Huê Viên tự hào là một trong những đại diện tiêu biểu của ngành thực phẩm Việt Nam tại Hội chợ Ẩm thực Quốc tế MIFB 2025 ở Malaysia.",                                                 Content = "<p>Tân Huê Viên tự hào là một trong những đại diện tiêu biểu của ngành thực phẩm Việt Nam tại Hội chợ Ẩm thực Quốc tế MIFB 2025 diễn ra tại Malaysia. Đây là cơ hội để Tân Huê Viên giới thiệu các sản phẩm truyền thống như bánh pía, lạp xưởng đến với bạn bè quốc tế.</p>",              Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 8, 7, 7, 0, 0, TimeSpan.FromHours(7)),   IsIndexable = true, MetaTitle = "Tân Huê Viên Tham Dự MIFB 2025 Malaysia",                                            MetaDescription = "Tân Huê Viên tham dự Hội chợ Ẩm thực Quốc tế MIFB 2025 tại Malaysia, quảng bá bánh pía và lạp xưởng Việt Nam." },
            new() { Title = "Háo Hức Đón Chào Lô Hàng Xuất Khẩu Của Tân Huê Viên Sang Hàn Quốc",           Slug = slugService.Generate("Hao Huc Don Chao Lo Hang Xuat Khau Cua Tan Hue Vien Sang Han Quoc"),           Excerpt = "Tân Huê Viên hoàn tất đóng thành công container xuất khẩu sang Hàn Quốc, tiếp tục mở rộng thị trường quốc tế.",                                                                              Content = "<p>Công ty TNHH Chế biến Thực phẩm Bánh Pía - Lạp Xưởng Tân Huê Viên đã hoàn tất đóng thành công container 20 feet và container 40 feet xuất khẩu sang thị trường Hàn Quốc. Đây là dấu mốc quan trọng trong hành trình mở rộng thị trường xuất khẩu của công ty.</p>",                          Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 7, 10, 7, 0, 0, TimeSpan.FromHours(7)),  IsIndexable = true, MetaTitle = "Tân Huê Viên Xuất Khẩu Sang Hàn Quốc",                                               MetaDescription = "Tân Huê Viên xuất khẩu thành công lô hàng bánh pía và lạp xưởng sang thị trường Hàn Quốc." },
            new() { Title = "Tân Huê Viên Tiếp Tục Xuất Khẩu Lô Hàng Sang Đức",                             Slug = slugService.Generate("Tan Hue Vien Tiep Tuc Xuat Khau Lo Hang Sang Duc"),                             Excerpt = "Lô hàng xuất khẩu thứ hai sang Đức trong năm 2025, dự kiến cập cảng Hamburg vào đầu tháng 8.",                                                                                               Content = "<p>Lô hàng xuất khẩu thứ hai sang Đức trong năm 2025 của Tân Huê Viên đã chính thức xuất bến, dự kiến cập cảng Hamburg vào ngày 5/8/2025. Đây là minh chứng cho sự tin tưởng ngày càng tăng của thị trường châu Âu đối với sản phẩm Tân Huê Viên.</p>",                                   Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 7, 8, 7, 0, 0, TimeSpan.FromHours(7)),   IsIndexable = true, MetaTitle = "Tân Huê Viên Xuất Khẩu Lô Hàng Thứ Hai Sang Đức 2025",                              MetaDescription = "Tân Huê Viên xuất khẩu lô hàng thứ hai sang Đức năm 2025, cập cảng Hamburg tháng 8." },
            new() { Title = "Tân Huê Viên Xuất Khẩu Lô Hàng Mới Sang Mỹ",                                   Slug = slugService.Generate("Tan Hue Vien Xuat Khau Lo Hang Moi Sang My"),                                   Excerpt = "Lô hàng hơn 15 mặt hàng đặc sản Tân Huê Viên xuất khẩu sang Mỹ, dự kiến cập bến Hoa Kỳ cuối tháng 7/2025.",                                                                                 Content = "<p>Tân Huê Viên vừa hoàn tất xuất khẩu lô hàng mới sang thị trường Mỹ bao gồm hơn 15 mặt hàng đặc sản – Lô hàng dự kiến cập bến Hoa Kỳ ngày 26/07/2025.</p>",                                                                                                                         Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 6, 26, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Tân Huê Viên Xuất Khẩu Sang Mỹ 2025",                                                MetaDescription = "Tân Huê Viên xuất khẩu hơn 15 mặt hàng đặc sản sang Mỹ, cập bến tháng 7/2025." },
            new() { Title = "Bánh Pía Chay Môn Tân Huê Viên Có Mặt Tại Costco",                              Slug = slugService.Generate("Banh Pia Chay Mon Tan Hue Vien Co Mat Tai Costco"),                              Excerpt = "Bánh pía chay môn Tân Huê Viên đã xuất khẩu thành công và sẽ sớm có mặt tại hệ thống siêu thị Costco.",                                                                                      Content = "<p>Bánh pía chay môn Tân Huê Viên đã được xuất khẩu thành công và sẽ sớm có mặt tại hệ thống siêu thị Costco – một trong những chuỗi bán lẻ lớn nhất thế giới.</p>",                                                                                                                Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 6, 3, 7, 0, 0, TimeSpan.FromHours(7)),  IsIndexable = true, MetaTitle = "Bánh Pía Chay Môn Tân Huê Viên Tại Costco",                                           MetaDescription = "Bánh pía chay môn Tân Huê Viên xuất khẩu thành công, có mặt tại hệ thống siêu thị Costco." },
            new() { Title = "Bánh Pía Tân Huê Viên Tại Costco Canada",                                       Slug = slugService.Generate("Banh Pia Tan Hue Vien Tai Costco Canada"),                                       Excerpt = "Dòng bánh pía đậu sầu riêng Tân Huê Viên đang trong trạng thái sold out tại hơn 10 nhà kho Costco Canada.",                                                                                   Content = "<p>Dòng bánh Pía Đậu - Sầu riêng Tân Huê Viên đang trong trạng thái sold out tại hơn 10 nhà kho Costco Canada. Đây là tin vui và cũng là niềm tự hào lớn của Tân Huê Viên khi sản phẩm truyền thống Việt Nam được người tiêu dùng Canada đón nhận nồng nhiệt.</p>",                Category = catExport, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2022, 6, 21, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Bánh Pía Tân Huê Viên Sold Out Tại Costco Canada",                                    MetaDescription = "Bánh pía đậu sầu riêng Tân Huê Viên sold out tại hơn 10 nhà kho Costco Canada – niềm tự hào đặc sản Việt." },
            new() { Title = "Tưng Bừng Khai Trương Đại Lý Tân Huê Viên Tại Phú Quốc, Tỉnh Kiên Giang",     Slug = slugService.Generate("Tuong Bung Khai Truong Dai Ly Tan Hue Vien Tai Phu Quoc Kien Giang"),     Excerpt = "Cửa hàng đại lý Tân Huê Viên tại thành phố đảo Phú Quốc chính thức khai trương, phục vụ du khách và người dân địa phương.",                                                               Content = "<p>Cửa hàng đại lý Tân Huê Viên tại thành phố đảo Phú Quốc, tỉnh Kiên Giang đã chính thức khai trương trong không khí tưng bừng. Sự kiện đánh dấu bước mở rộng mạng lưới phân phối của Tân Huê Viên đến điểm du lịch nổi tiếng nhất Việt Nam.</p>",                                  Category = catNews,   Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2022, 6, 10, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Khai Trương Đại Lý Tân Huê Viên Tại Phú Quốc",                                        MetaDescription = "Đại lý Tân Huê Viên tại Phú Quốc chính thức khai trương, phục vụ du khách mua đặc sản bánh pía lạp xưởng." },
            new() { Title = "Ra Mắt Dòng Sản Phẩm Mới 2025: Hoàng Kim, Bánh Love, Bánh Liên Hoa",           Slug = slugService.Generate("Ra Mat Dong San Pham Moi 2025 Hoang Kim Banh Love Banh Lien Hoa"),           Excerpt = "Tân Huê Viên chính thức ra mắt loạt sản phẩm mới năm 2025 với thiết kế sang trọng và hương vị đặc sắc.",                                                                                   Content = "<p>Tân Huê Viên chính thức giới thiệu dòng sản phẩm mới năm 2025 bao gồm: Hoàng Kim Đậu - Môn, Hoàng Kim Đậu - Dứa, Bánh Kim Ngân, Bánh Tiểu Long Châu, Bánh Love, Bánh Tuyết Liên và Bánh Liên Hoa.</p>",                                                                               Category = catProduct, Status = PostStatus.Published, PublishedAt = new DateTimeOffset(2025, 1, 15, 7, 0, 0, TimeSpan.FromHours(7)), IsIndexable = true, MetaTitle = "Sản Phẩm Mới 2025 Tân Huê Viên - Hoàng Kim, Love, Liên Hoa",                          MetaDescription = "Tân Huê Viên ra mắt loạt sản phẩm mới 2025: Hoàng Kim, Bánh Love, Bánh Liên Hoa – thiết kế sang trọng, hương vị đặc sắc." },
        };

        context.Posts.AddRange(posts);

        // ── Store Locations ───────────────────────────────────────────────────
        context.StoreLocations.AddRange(
            new StoreLocation
            {
                Name           = "Trụ sở chính Tân Huê Viên - Cần Thơ",
                FullAddress    = "153 Quốc lộ 1A, ấp Phụng Hiệp, xã An Ninh, Thành phố Cần Thơ",
                ProvinceOrCity = "Cần Thơ",
                Country        = "Việt Nam",
                LandlinePhone  = "(0299) 3623700",
                MobilePhone    = "(0299) 3821322",
                Latitude       = 10.0452,
                Longitude      = 105.7469,
                LocationType   = StoreLocationType.Showroom,
                RegionType     = StoreRegionType.Domestic,
                IsActive       = true,
                SortOrder      = 1,
            },
            new StoreLocation
            {
                Name           = "Đại lý Tân Huê Viên - Phú Quốc",
                FullAddress    = "Thành phố Phú Quốc, tỉnh Kiên Giang",
                ProvinceOrCity = "Kiên Giang",
                Country        = "Việt Nam",
                LocationType   = StoreLocationType.Dealer,
                RegionType     = StoreRegionType.Domestic,
                IsActive       = true,
                SortOrder      = 2,
            }
        );

        await context.SaveChangesAsync(CancellationToken.None);
    }
}
