using SPage.Domain.Common;

namespace SPage.Domain.Entities.Product;

public sealed class Product : BaseAuditableEntity, ISeoEntity
{
    public string Name { get; set; } = string.Empty;
    public string Slug { get; set; } = string.Empty;
    public string? MetaTitle { get; set; }
    public string? MetaDescription { get; set; }
    public string? CanonicalUrl { get; set; }
    public bool IsIndexable { get; set; } = true;

    public string? Description { get; set; }
    public string? ShortDescription { get; set; }
    public decimal Price { get; set; }
    public decimal? SalePrice { get; set; }
    public string? SKU { get; set; }
    public bool IsActive { get; set; } = true;
    public bool IsNew { get; set; } = false;
    public bool IsFeatured { get; set; } = false;
    public bool IsPromotion { get; set; } = false;
    public int SortOrder { get; set; } = 0;

    public int CategoryId { get; set; }
    public ProductCategory? Category { get; set; }

    public ICollection<ProductImage> Images { get; set; } = [];
    public ICollection<ProductAttributeValue> AttributeValues { get; set; } = [];
}

public sealed class ProductImage : BaseEntity
{
    public int ProductId { get; set; }
    public Product Product { get; set; } = null!;
    public string ImageUrl { get; set; } = string.Empty;      // .webp
    public string? AltText { get; set; }
    public int SortOrder { get; set; } = 0;
    public bool IsPrimary { get; set; } = false;
    // Responsive srcset paths — auto-generated by ImageSharp
    public string? ImageUrl400w { get; set; }
    public string? ImageUrl800w { get; set; }
    public string? ImageUrl1200w { get; set; }
}

public sealed class ProductAttribute : BaseEntity
{
    public string Name { get; set; } = string.Empty;
    public ICollection<ProductAttributeValue> Values { get; set; } = [];
}

public sealed class ProductAttributeValue : BaseEntity
{
    public int ProductId { get; set; }
    public Product Product { get; set; } = null!;
    public int AttributeId { get; set; }
    public ProductAttribute Attribute { get; set; } = null!;
    public string Value { get; set; } = string.Empty;
}
